tasks:
  - before: curl -fsSL https://deno.land/install.sh | sh -s -- -y; . "/home/gitpod/.deno/env"
    init: deno install && cargo build
    command: cargo watch -i "src/**.js" -i "tstypes/**.d.ts" -x "run -- test.js"
