name: Publish JSR package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install build dependencies
        run: npm i
      - name: Build TypeScript code
        run: npm run build-ts

  publish-jsr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install build dependencies
        run: npm i
      - name: Build TypeScript code
        run: npm run build-ts
      - name: Publish to JSR
        run: npx jsr publish --allow-slow-types --allow-dirty
